name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
  IMAGE_NAME: chat-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: 'echo "$ENV" > src/.env'
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Azure ACR Login
        uses: azure/cli@v2
        with:
          inlineScript: |
            cd src/
            az acr build --image ${{ env.IMAGE_NAME }}:latest1 --registry ${{ env.AZURE_CONTAINER_REGISTRY }}  --file Dockerfile .

      # - name: Login to ACR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
      #     username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
      #     password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      # - name: Build and push Docker image
      #   run: |
      #     cd src/
      #     docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
      #     docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest